# Change these first
owner: sebastiangollob
repo: uptime-monitor

sites:
  - name: BingePilot
    url: https://bingepilot.com
    slug: bingepilot
  - name: Keycloak
    url: $KEYCLOAK_URL
    slug: keycloak
  - name: Gameserver
    url: $GAMESERVER_URL
    slug: gameserver
  - name: N8n
    url: $N8N_URL
    slug: n8n
  - name: Database
    check: "tcp-ping"
    url: $DB_IP
    port: $DB_PORT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gollob.dev
  theme: dark
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status Dashboard
  navbar:
    - title: Service Status
      href: /
    - title: GitHub Repository
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
